version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env
    ports:
      - 4200:4200
    restart: always
    hostname: app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
